apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seldon-core-analytics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://chritter.github.io/charts
    chart: seldon-core-analytics
    targetRevision: 1.11.0-dev
    path: .
  destination:
    namespace: seldon-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
