apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seldon-core
  namespace: argocd
spec:
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: seldondeployments.machinelearning.seldon.io
    jsonPointers:
    - /spec
    - /status
    - /metadata/labels
  project: default
  source:
    repoURL: https://chritter.github.io/charts
    chart: seldon-core-operator
    targetRevision: 1.10.0
    path: .
  destination:
    namespace: seldon-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
